version: '2'


services:
  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=canvas
      - POSTGRES_PASSWORD=canvas123
      - POSTGRES_DB=canvas

  web:
    build: .
    command: '/usr/bin/supervisord -n -c /etc/supervisord.conf'
    volumes:
      - gems:/gems
    ports:
      - "80:80"
    depends_on:
      - db
    dns:
      - 8.8.8.8
    environment:
      - CANVAS_LMS_ADMIN_EMAIL=hieu.hoang@eastagile.com
      - CANVAS_LMS_ADMIN_PASSWORD=aA@12345
      - CANVAS_LMS_ADMIN_ACCOUNT=admin
      - CANVAS_LMS_STATS_COLLECTION=opt_out

volumes:
  bundle:
  gems:
