version: '2'


services:
  db:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=canvas
      - POSTGRES_PASSWORD=aA@12345
      - POSTGRES_DB=canvas

  web:
    build: .
    command: '/usr/bin/supervisord -n -c /etc/supervisord.conf'
    volumes:
      - gems:/gems
      - ./canvas-lms:/canvas
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
    environment:
      - CANVAS_LMS_ADMIN_EMAIL=involvio+lti@eastagile.com
      - CANVAS_LMS_ADMIN_PASSWORD=aA@12345
      - CANVAS_LMS_ADMIN_ACCOUNT=admin
      - CANVAS_LMS_STATS_COLLECTION=opt_out

  delayed_jobs:
    build: .
    command: 'script/canvas_init run'
    volumes:
      - gems:/gems
      - ./canvas-lms:/canvas
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
    environment:
      - CANVAS_LMS_ADMIN_EMAIL=involvio+lti@eastagile.com
      - CANVAS_LMS_ADMIN_PASSWORD=aA@12345
      - CANVAS_LMS_ADMIN_ACCOUNT=admin
      - CANVAS_LMS_STATS_COLLECTION=opt_out
  redis:
      image: redis

volumes:
  bundle:
  gems:
  app:
